### PR TITLE
Feat: new layout! 🔥

### PR DESCRIPTION
**Pull request by thinkverse**
### Why is this PR needed?

This PR updates the layout to use tailwind and be a bit more responsive also removed some now unused styles and fixed how the landing page cards behave on the new layout.

### Feature

This new layout is a two-column/row responsive design based on flexbox, giving you the freedom to add and remove paddings and margins inside each column/row respectively, the `<main>` content also respects the width of the `<header>` so it grows when it needs to and shrinks when it needs to. 👍

### Included in PR.

- Removed unused style classes
- Updated layout to use tailwind
- Fixed landing page cards

---

Hope you like it, happy designing. 👋&nbsp;&nbsp;🙂

### CODE REVIEW

**Comment by bdougie** [comment]
Thanks so much for this @thinkverse. I found some issues with padding and leaving screenshots. Looks like the smaller screens are not getting any padding on the left. 

Screen Shot 2020-08-31 at 3 43 12 PM
Screen Shot 2020-08-31 at 3 42 58 PM

**Comment by thinkverse** [comment]
Yes, that is because with this layout you can change the padding and margin on a page-by-page basis by adding a child element after `<Layout>` as demonstrated in `pages/index.tsx`, I figured you'd like to make all the fine tweaking yourself so I left it out. 🙂

**Comment by bdougie** [comment]
Yep, I can tweak this. I might merge this on stream and finish it tomorrow.

**Comment by bdougie** [comment]
Rechecked this, and it is not broken. Hmmm, weird, but if I see the padding issue again, I know where to look.

**Pull request merged**
